//
//  BashShellIntegration.swift
//  gmax
//
//  Created by Gale Williams on 4/24/26.
//

import Foundation

enum BashShellIntegration {
    nonisolated static let rcfileEnvironmentKey = "GMAX_BASH_INTEGRATION_RCFILE"

    nonisolated static func environmentOverlay(
        shellExecutable: String,
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        guard ShellIntegrationSupport.shellName(for: shellExecutable) == "bash" else {
            return [:]
        }

        let originalHomeDirectory = ShellIntegrationSupport.originalHomeDirectory(from: baseEnvironment)
        guard
            let rcfileURL = try? install(
                originalHomeDirectory: originalHomeDirectory,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "GMAX_ORIGINAL_HOME": originalHomeDirectory,
            rcfileEnvironmentKey: rcfileURL.path,
            "GMAX_SHELL_INTEGRATION": "1",
        ]
    }

    nonisolated static func launchArguments(environment: [String: String]) -> [String]? {
        guard let rcfilePath = environment[rcfileEnvironmentKey], !rcfilePath.isEmpty else {
            return nil
        }

        return ["--rcfile", rcfilePath, "-i"]
    }

    nonisolated static func handoffEnvironment(
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        let originalHomeDirectory = ShellIntegrationSupport.originalHomeDirectory(from: baseEnvironment)
        guard
            let rcfileURL = try? install(
                originalHomeDirectory: originalHomeDirectory,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "GMAX_ORIGINAL_HOME": originalHomeDirectory,
            rcfileEnvironmentKey: rcfileURL.path,
        ]
    }

    nonisolated static func install(
        originalHomeDirectory: String,
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) throws -> URL {
        let wrapperDirectory = try ShellIntegrationSupport.wrapperDirectoryURL(
            shellName: "bash",
            fileManager: fileManager,
            rootDirectory: rootDirectory,
        )
        try fileManager.createDirectory(at: wrapperDirectory, withIntermediateDirectories: true)

        let rcfileURL = wrapperDirectory.appendingPathComponent("gmax-bashrc")
        try ShellIntegrationSupport.write(
            integrationScript(originalHomeDirectory: originalHomeDirectory),
            to: rcfileURL,
            fileManager: fileManager,
        )
        return rcfileURL
    }

    private nonisolated static func integrationScript(originalHomeDirectory: String) -> String {
        #"""
        # Generated by gmax. Recreates login-style bash startup, then adds lightweight prompt markers.
        if [[ -n "${GMAX_BASH_SHELL_INTEGRATION_LOADED:-}" ]]; then
          return
        fi
        export GMAX_BASH_SHELL_INTEGRATION_LOADED=1

        if [[ -f /etc/profile ]]; then
          . /etc/profile
        fi

        if [[ -f "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bash_profile" ]]; then
          . "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bash_profile"
        elif [[ -f "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bash_login" ]]; then
          . "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bash_login"
        elif [[ -f "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.profile" ]]; then
          . "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.profile"
        elif [[ -f "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bashrc" ]]; then
          . "${GMAX_ORIGINAL_HOME:-\#(originalHomeDirectory)}/.bashrc"
        fi

        gmax_emit_osc() {
          printf '\033]%s\a' "$1"
        }

        gmax_emit_cwd() {
          local absolute_path="${PWD}"
          absolute_path=${absolute_path//\%/%25}
          absolute_path=${absolute_path// /%20}
          absolute_path=${absolute_path//#/%23}
          absolute_path=${absolute_path//\?/%3F}
          gmax_emit_osc "7;file://${HOSTNAME:-localhost}${absolute_path}"
        }

        gmax_preexec_trap() {
          if [[ -n "${GMAX_IN_PROMPT_COMMAND:-}" ]]; then
            return
          fi

          if [[ -n "${GMAX_AT_PROMPT:-}" ]]; then
            unset GMAX_AT_PROMPT
            if [[ -z "${GMAX_SHELL_COMMAND_ACTIVE:-}" ]]; then
              GMAX_SHELL_COMMAND_ACTIVE=1
              gmax_emit_osc '133;C'
            fi
          fi
        }

        gmax_prompt_command() {
          local status=$?
          export GMAX_IN_PROMPT_COMMAND=1

          if [[ -n "${GMAX_ORIGINAL_PROMPT_COMMAND:-}" ]]; then
            eval "${GMAX_ORIGINAL_PROMPT_COMMAND}"
          fi

          if [[ -n "${GMAX_SHELL_COMMAND_ACTIVE:-}" ]]; then
            gmax_emit_osc "133;D;${status}"
            unset GMAX_SHELL_COMMAND_ACTIVE
          fi

          gmax_emit_cwd
          gmax_emit_osc '133;A'
          export GMAX_AT_PROMPT=1
          unset GMAX_IN_PROMPT_COMMAND
        }

        if [[ -n "${PROMPT_COMMAND:-}" ]]; then
          export GMAX_ORIGINAL_PROMPT_COMMAND="${PROMPT_COMMAND}"
        fi
        PROMPT_COMMAND='gmax_prompt_command'
        trap 'gmax_preexec_trap' DEBUG

        gmax() {
          local subcommand="$1"
          shift || true

          case "$subcommand" in
            bash)
              if [[ -n "${GMAX_BASH_INTEGRATION_RCFILE:-}" ]]; then
                exec /bin/bash --rcfile "${GMAX_BASH_INTEGRATION_RCFILE}" -i "$@"
              fi
              printf '%s\n' "gmax bash is unavailable because no integrated bash rcfile is configured for this pane." >&2
              return 1
              ;;
            zsh)
              if [[ -n "${GMAX_ZSH_INTEGRATION_ZDOTDIR:-}" ]]; then
                export ZDOTDIR="${GMAX_ZSH_INTEGRATION_ZDOTDIR}"
                exec /bin/zsh -l "$@"
              fi
              printf '%s\n' "gmax zsh is unavailable because no integrated zsh wrapper is configured for this pane." >&2
              return 1
              ;;
            fish)
              if [[ -n "${GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME:-}" ]]; then
                export XDG_CONFIG_HOME="${GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME}"
                exec fish -l "$@"
              fi
              printf '%s\n' "gmax fish is unavailable because no integrated fish wrapper is configured for this pane." >&2
              return 1
              ;;
            "")
              printf '%s\n' "usage: gmax <bash|zsh|fish>" >&2
              return 1
              ;;
            *)
              printf 'unknown gmax shell handoff: %s\n' "$subcommand" >&2
              return 1
              ;;
          esac
        }
        """#
    }
}
