//
//  FishShellIntegration.swift
//  gmax
//
//  Created by Gale Williams on 4/24/26.
//

import Foundation

enum FishShellIntegration {
    nonisolated static let wrapperConfigHomeEnvironmentKey = "GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME"

    nonisolated static func environmentOverlay(
        shellExecutable: String,
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        guard ShellIntegrationSupport.shellName(for: shellExecutable) == "fish" else {
            return [:]
        }

        let originalXDGConfigHome = ShellIntegrationSupport.originalXDGConfigHome(from: baseEnvironment)
        guard
            let wrapperConfigHome = try? install(
                originalXDGConfigHome: originalXDGConfigHome,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "XDG_CONFIG_HOME": wrapperConfigHome.path,
            "GMAX_ORIGINAL_XDG_CONFIG_HOME": originalXDGConfigHome,
            wrapperConfigHomeEnvironmentKey: wrapperConfigHome.path,
            "GMAX_SHELL_INTEGRATION": "1",
        ]
    }

    nonisolated static func handoffEnvironment(
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        let originalXDGConfigHome = ShellIntegrationSupport.originalXDGConfigHome(from: baseEnvironment)
        guard
            let wrapperConfigHome = try? install(
                originalXDGConfigHome: originalXDGConfigHome,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "GMAX_ORIGINAL_XDG_CONFIG_HOME": originalXDGConfigHome,
            wrapperConfigHomeEnvironmentKey: wrapperConfigHome.path,
        ]
    }

    nonisolated static func install(
        originalXDGConfigHome: String,
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) throws -> URL {
        let wrapperDirectory = try ShellIntegrationSupport.wrapperDirectoryURL(
            shellName: "fish",
            fileManager: fileManager,
            rootDirectory: rootDirectory,
        )
        let wrapperConfigHome = wrapperDirectory.appendingPathComponent("xdg", isDirectory: true)
        let fishConfigDirectory = wrapperConfigHome.appendingPathComponent("fish", isDirectory: true)
        try fileManager.createDirectory(at: fishConfigDirectory, withIntermediateDirectories: true)

        try ShellIntegrationSupport.write(
            configScript(originalXDGConfigHome: originalXDGConfigHome),
            to: fishConfigDirectory.appendingPathComponent("config.fish"),
            fileManager: fileManager,
        )
        try ShellIntegrationSupport.write(
            integrationScript(),
            to: fishConfigDirectory.appendingPathComponent("gmax-shell-integration.fish"),
            fileManager: fileManager,
        )
        return wrapperConfigHome
    }

    private nonisolated static func configScript(originalXDGConfigHome: String) -> String {
        #"""
        # Generated by gmax. Sources the user's original fish config, then enables lightweight prompt markers.
        set -l gmax_original_xdg_config_home "$GMAX_ORIGINAL_XDG_CONFIG_HOME"
        if test -z "$gmax_original_xdg_config_home"
            set gmax_original_xdg_config_home "\#(originalXDGConfigHome)"
        end

        set -l gmax_original_fish_config_dir "$gmax_original_xdg_config_home/fish"
        if test -d "$gmax_original_fish_config_dir/conf.d"
            for file in $gmax_original_fish_config_dir/conf.d/*.fish
                if test -f "$file"
                    source "$file"
                end
            end
        end

        if test -f "$gmax_original_fish_config_dir/config.fish"
            source "$gmax_original_fish_config_dir/config.fish"
        end

        source (status dirname)/gmax-shell-integration.fish
        """#
    }

    private nonisolated static func integrationScript() -> String {
        #"""
        # Generated by gmax. Adds lightweight prompt and cwd markers for fish sessions.
        if set -q GMAX_FISH_SHELL_INTEGRATION_LOADED
            return
        end
        set -g GMAX_FISH_SHELL_INTEGRATION_LOADED 1
        set -g GMAX_SHELL_COMMAND_ACTIVE 0

        function gmax_emit_osc
            printf '\e]%s\a' "$argv[1]"
        end

        function gmax_emit_cwd
            set -l absolute_path "$PWD"
            set absolute_path (string replace -a '%' '%25' -- "$absolute_path")
            set absolute_path (string replace -a ' ' '%20' -- "$absolute_path")
            set absolute_path (string replace -a '#' '%23' -- "$absolute_path")
            set absolute_path (string replace -a '?' '%3F' -- "$absolute_path")
            gmax_emit_osc "7;file://localhost$absolute_path"
        end

        function gmax_prompt_started --on-event fish_prompt
            gmax_emit_cwd
            gmax_emit_osc '133;A'
        end

        function gmax_command_started --on-event fish_preexec
            set -g GMAX_SHELL_COMMAND_ACTIVE 1
            gmax_emit_osc '133;C'
        end

        function gmax_command_finished --on-event fish_postexec
            if test "$GMAX_SHELL_COMMAND_ACTIVE" = "1"
                gmax_emit_osc "133;D;$status"
                set -g GMAX_SHELL_COMMAND_ACTIVE 0
            end
        end

        function gmax_command_errored --on-event fish_posterror
            if test "$GMAX_SHELL_COMMAND_ACTIVE" = "1"
                gmax_emit_osc "133;D;$status"
                set -g GMAX_SHELL_COMMAND_ACTIVE 0
            end
        end

        function gmax_pwd_changed --on-variable PWD
            gmax_emit_cwd
        end

        function gmax
            set -l subcommand "$argv[1]"
            set -e argv[1]

            switch "$subcommand"
                case bash
                    if set -q GMAX_BASH_INTEGRATION_RCFILE
                        exec /bin/bash --rcfile "$GMAX_BASH_INTEGRATION_RCFILE" -i $argv
                    end
                    printf '%s\n' "gmax bash is unavailable because no integrated bash rcfile is configured for this pane." >&2
                    return 1
                case zsh
                    if set -q GMAX_ZSH_INTEGRATION_ZDOTDIR
                        set -gx ZDOTDIR "$GMAX_ZSH_INTEGRATION_ZDOTDIR"
                        exec /bin/zsh -l $argv
                    end
                    printf '%s\n' "gmax zsh is unavailable because no integrated zsh wrapper is configured for this pane." >&2
                    return 1
                case fish
                    if set -q GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME
                        set -gx XDG_CONFIG_HOME "$GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME"
                        exec fish -l $argv
                    end
                    printf '%s\n' "gmax fish is unavailable because no integrated fish wrapper is configured for this pane." >&2
                    return 1
                case ''
                    printf '%s\n' "usage: gmax <bash|zsh|fish>" >&2
                    return 1
                case '*'
                    printf 'unknown gmax shell handoff: %s\n' "$subcommand" >&2
                    return 1
            end
        end
        """#
    }
}
