//
//  ZshShellIntegration.swift
//  gmax
//
//  Created by Gale Williams on 4/24/26.
//

import Foundation

enum ZshShellIntegration {
    nonisolated static func environmentOverlay(
        shellExecutable: String,
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        guard URL(fileURLWithPath: shellExecutable).lastPathComponent == "zsh" else {
            return [:]
        }

        let originalZdotdir = baseEnvironment["ZDOTDIR"] ?? NSHomeDirectory()
        guard
            let wrapperDirectory = try? install(
                originalZdotdir: originalZdotdir,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "ZDOTDIR": wrapperDirectory.path,
            "GMAX_ORIGINAL_ZDOTDIR": originalZdotdir,
            "GMAX_SHELL_INTEGRATION": "1",
        ]
    }

    nonisolated static func install(
        originalZdotdir: String,
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) throws -> URL {
        let wrapperDirectory = try wrapperDirectoryURL(
            fileManager: fileManager,
            rootDirectory: rootDirectory,
        )
        try fileManager.createDirectory(at: wrapperDirectory, withIntermediateDirectories: true)

        try write(
            """
            # Generated by gmax. Sources the user's real zshenv first.
            \(sourceOriginalDotfile(named: ".zshenv"))
            """,
            to: wrapperDirectory.appendingPathComponent(".zshenv"),
            fileManager: fileManager,
        )
        try write(
            """
            # Generated by gmax. Sources the user's real zprofile first.
            \(sourceOriginalDotfile(named: ".zprofile"))
            """,
            to: wrapperDirectory.appendingPathComponent(".zprofile"),
            fileManager: fileManager,
        )
        try write(
            """
            # Generated by gmax. Sources the user's real zshrc first, then enables gmax shell markers.
            \(sourceOriginalDotfile(named: ".zshrc"))
            source "${ZDOTDIR}/gmax-shell-integration.zsh"
            """,
            to: wrapperDirectory.appendingPathComponent(".zshrc"),
            fileManager: fileManager,
        )
        try write(
            """
            # Generated by gmax. Sources the user's real zlogin first.
            \(sourceOriginalDotfile(named: ".zlogin"))
            """,
            to: wrapperDirectory.appendingPathComponent(".zlogin"),
            fileManager: fileManager,
        )
        try write(
            integrationScript(originalZdotdir: originalZdotdir),
            to: wrapperDirectory.appendingPathComponent("gmax-shell-integration.zsh"),
            fileManager: fileManager,
        )

        return wrapperDirectory
    }

    private nonisolated static func wrapperDirectoryURL(
        fileManager: FileManager,
        rootDirectory: URL?,
    ) throws -> URL {
        if let rootDirectory {
            return rootDirectory.appendingPathComponent("zsh", isDirectory: true)
        }

        let applicationSupportDirectory = try fileManager
            .url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            .appendingPathComponent("gmax", isDirectory: true)
            .appendingPathComponent("ShellIntegration", isDirectory: true)
        return applicationSupportDirectory.appendingPathComponent("zsh", isDirectory: true)
    }

    private nonisolated static func write(
        _ content: String,
        to url: URL,
        fileManager: FileManager,
    ) throws {
        let data = Data(content.utf8)
        if fileManager.fileExists(atPath: url.path),
           let existingData = fileManager.contents(atPath: url.path),
           existingData == data {
            return
        }

        try data.write(to: url, options: .atomic)
    }

    private nonisolated static func sourceOriginalDotfile(named dotfileName: String) -> String {
        """
        if [[ -n "${GMAX_ORIGINAL_ZDOTDIR:-}" && "${GMAX_ORIGINAL_ZDOTDIR}" != "${ZDOTDIR:-}" ]]; then
          if [[ -f "${GMAX_ORIGINAL_ZDOTDIR}/\(dotfileName)" ]]; then
            source "${GMAX_ORIGINAL_ZDOTDIR}/\(dotfileName)"
          fi
        fi
        """
    }

    private nonisolated static func integrationScript(originalZdotdir: String) -> String {
        #"""
        # Generated by gmax. Adds lightweight prompt and cwd markers for zsh sessions.
        if [[ -n "${GMAX_SHELL_INTEGRATION_LOADED:-}" ]]; then
          return
        fi
        typeset -g GMAX_SHELL_INTEGRATION_LOADED=1
        typeset -gi GMAX_SHELL_COMMAND_ACTIVE=0

        gmax_emit_osc() {
          printf '\033]%s\a' "$1"
        }

        gmax_emit_cwd() {
          local absolute_path="${PWD:A}"
          absolute_path=${absolute_path//\%/%25}
          absolute_path=${absolute_path// /%20}
          absolute_path=${absolute_path//#/%23}
          absolute_path=${absolute_path//\?/%3F}
          gmax_emit_osc "7;file://${HOST:-localhost}${absolute_path}"
        }

        gmax_precmd() {
          local status=$?
          if (( GMAX_SHELL_COMMAND_ACTIVE )); then
            gmax_emit_osc "133;D;${status}"
            GMAX_SHELL_COMMAND_ACTIVE=0
          fi
          gmax_emit_cwd
          gmax_emit_osc '133;A'
        }

        gmax_preexec() {
          GMAX_SHELL_COMMAND_ACTIVE=1
          gmax_emit_osc '133;C'
        }

        autoload -Uz add-zsh-hook
        add-zsh-hook precmd gmax_precmd
        add-zsh-hook preexec gmax_preexec
        add-zsh-hook chpwd gmax_emit_cwd
        """#
    }
}
