//
//  ZshShellIntegration.swift
//  gmax
//
//  Created by Gale Williams on 4/24/26.
//

import Foundation

enum ZshShellIntegration {
    nonisolated static let wrapperZdotdirEnvironmentKey = "GMAX_ZSH_INTEGRATION_ZDOTDIR"

    nonisolated static func environmentOverlay(
        shellExecutable: String,
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        guard ShellIntegrationSupport.shellName(for: shellExecutable) == "zsh" else {
            return [:]
        }

        let originalZdotdir = baseEnvironment["GMAX_ORIGINAL_ZDOTDIR"]
            ?? baseEnvironment["ZDOTDIR"]
            ?? NSHomeDirectory()
        guard
            let wrapperDirectory = try? install(
                originalZdotdir: originalZdotdir,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            "ZDOTDIR": wrapperDirectory.path,
            "GMAX_ORIGINAL_ZDOTDIR": originalZdotdir,
            wrapperZdotdirEnvironmentKey: wrapperDirectory.path,
            "GMAX_SHELL_INTEGRATION": "1",
        ]
    }

    nonisolated static func handoffEnvironment(
        baseEnvironment: [String: String],
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) -> [String: String] {
        let originalZdotdir = baseEnvironment["GMAX_ORIGINAL_ZDOTDIR"]
            ?? baseEnvironment["ZDOTDIR"]
            ?? NSHomeDirectory()
        guard
            let wrapperDirectory = try? install(
                originalZdotdir: originalZdotdir,
                fileManager: fileManager,
                rootDirectory: rootDirectory,
            )
        else {
            return [:]
        }

        return [
            wrapperZdotdirEnvironmentKey: wrapperDirectory.path,
            "GMAX_ORIGINAL_ZDOTDIR": originalZdotdir,
        ]
    }

    nonisolated static func install(
        originalZdotdir: String,
        fileManager: FileManager = .default,
        rootDirectory: URL? = nil,
    ) throws -> URL {
        let wrapperDirectory = try ShellIntegrationSupport.wrapperDirectoryURL(
            shellName: "zsh",
            fileManager: fileManager,
            rootDirectory: rootDirectory,
        )
        try fileManager.createDirectory(at: wrapperDirectory, withIntermediateDirectories: true)

        try ShellIntegrationSupport.write(
            """
            # Generated by gmax. Sources the user's real zshenv first.
            typeset -g GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR="${ZDOTDIR:-}"
            \(sourceOriginalDotfile(named: ".zshenv"))
            export ZDOTDIR="${GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR}"
            """,
            to: wrapperDirectory.appendingPathComponent(".zshenv"),
            fileManager: fileManager,
        )
        try ShellIntegrationSupport.write(
            """
            # Generated by gmax. Sources the user's real zprofile first.
            typeset -g GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR="${ZDOTDIR:-}"
            \(sourceOriginalDotfile(named: ".zprofile"))
            export ZDOTDIR="${GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR}"
            """,
            to: wrapperDirectory.appendingPathComponent(".zprofile"),
            fileManager: fileManager,
        )
        try ShellIntegrationSupport.write(
            """
            # Generated by gmax. Sources the user's real zshrc first, then enables gmax shell markers.
            typeset -g GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR="${ZDOTDIR:-}"
            \(sourceOriginalDotfile(named: ".zshrc"))
            source "${GMAX_SHELL_INTEGRATION_WRAPPER_ZDOTDIR}/gmax-shell-integration.zsh"
            """,
            to: wrapperDirectory.appendingPathComponent(".zshrc"),
            fileManager: fileManager,
        )
        try ShellIntegrationSupport.write(
            """
            # Generated by gmax. Sources the user's real zlogin first.
            \(sourceOriginalDotfile(named: ".zlogin"))
            """,
            to: wrapperDirectory.appendingPathComponent(".zlogin"),
            fileManager: fileManager,
        )
        try ShellIntegrationSupport.write(
            integrationScript(originalZdotdir: originalZdotdir),
            to: wrapperDirectory.appendingPathComponent("gmax-shell-integration.zsh"),
            fileManager: fileManager,
        )

        return wrapperDirectory
    }

    private nonisolated static func sourceOriginalDotfile(named dotfileName: String) -> String {
        """
        if [[ -n "${GMAX_ORIGINAL_ZDOTDIR:-}" && "${GMAX_ORIGINAL_ZDOTDIR}" != "${ZDOTDIR:-}" ]]; then
          if [[ -f "${GMAX_ORIGINAL_ZDOTDIR}/\(dotfileName)" ]]; then
            source "${GMAX_ORIGINAL_ZDOTDIR}/\(dotfileName)"
          fi
        fi
        """
    }

    private nonisolated static func integrationScript(originalZdotdir: String) -> String {
        #"""
        # Generated by gmax. Adds lightweight prompt and cwd markers for zsh sessions.
        if [[ -n "${GMAX_ZSH_SHELL_INTEGRATION_LOADED:-}" ]]; then
          return
        fi
        typeset -g GMAX_ZSH_SHELL_INTEGRATION_LOADED=1
        typeset -gi GMAX_SHELL_COMMAND_ACTIVE=0

        gmax_emit_osc() {
          printf '\033]%s\a' "$1"
        }

        gmax_emit_cwd() {
          local absolute_path="${PWD:A}"
          absolute_path=${absolute_path//\%/%25}
          absolute_path=${absolute_path// /%20}
          absolute_path=${absolute_path//#/%23}
          absolute_path=${absolute_path//\?/%3F}
          gmax_emit_osc "7;file://${HOST:-localhost}${absolute_path}"
        }

        gmax_precmd() {
          local exit_status=$?
          if (( GMAX_SHELL_COMMAND_ACTIVE )); then
            gmax_emit_osc "133;D;${exit_status}"
            GMAX_SHELL_COMMAND_ACTIVE=0
          fi
          gmax_emit_cwd
          gmax_emit_osc '133;A'
        }

        gmax_preexec() {
          GMAX_SHELL_COMMAND_ACTIVE=1
          gmax_emit_osc '133;C'
        }

        gmax() {
          local subcommand="$1"
          shift || true

          case "$subcommand" in
            bash)
              if [[ -n "${GMAX_BASH_INTEGRATION_RCFILE:-}" ]]; then
                exec /bin/bash --rcfile "${GMAX_BASH_INTEGRATION_RCFILE}" -i "$@"
              fi
              print -u2 "gmax bash is unavailable because no integrated bash rcfile is configured for this pane."
              return 1
              ;;
            zsh)
              if [[ -n "${GMAX_ZSH_INTEGRATION_ZDOTDIR:-}" ]]; then
                export ZDOTDIR="${GMAX_ZSH_INTEGRATION_ZDOTDIR}"
                exec /bin/zsh -l "$@"
              fi
              print -u2 "gmax zsh is unavailable because no integrated zsh wrapper is configured for this pane."
              return 1
              ;;
            fish)
              if [[ -n "${GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME:-}" ]]; then
                export XDG_CONFIG_HOME="${GMAX_FISH_INTEGRATION_XDG_CONFIG_HOME}"
                exec fish -l "$@"
              fi
              print -u2 "gmax fish is unavailable because no integrated fish wrapper is configured for this pane."
              return 1
              ;;
            "")
              print -u2 "usage: gmax <bash|zsh|fish>"
              return 1
              ;;
            *)
              print -u2 "unknown gmax shell handoff: ${subcommand}"
              return 1
              ;;
          esac
        }

        autoload -Uz add-zsh-hook
        add-zsh-hook precmd gmax_precmd
        add-zsh-hook preexec gmax_preexec
        add-zsh-hook chpwd gmax_emit_cwd
        """#
    }
}
